import styles from '../styles/Home.module.scss';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.marketing}>
        <div className={`${styles.imagePlaceholder} ${styles.spanTwo}`} />
        <div className={styles.imagePlaceholder} />
        <div className={styles.imagePlaceholder} />
        <div className={styles.imagePlaceholder} />
        <div className={styles.imagePlaceholder} />
        <div className={`${styles.imagePlaceholder} ${styles.spanTwo}`} />
        <div className={styles.imagePlaceholder} />
        <div className={styles.imagePlaceholder} />
      </section>
    </div>
  );
}
